# Generated by Django 5.1.3 on 2024-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serving_size', models.PositiveIntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=20)),
                ('calories', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('proteins', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
            ],
        ),
    ]
